import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import { Inter } from "next/font/google";
import "../styles/globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "RAWN PRO — Human Performance Advisor",
  description:
    "RAWN PRO é um conselheiro de performance humana com precisão científica e empatia real.",
>>>>>>> 0edce9270c3332c42d0ddadaf5aa199cc416f7e7
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
=======
      <body className={`${inter.variable} antialiased bg-[#F8F9FA] text-[#1E1E1E]`}>
>>>>>>> 0edce9270c3332c42d0ddadaf5aa199cc416f7e7
        {children}
      </body>
    </html>
  );
}
